app:
  environment: ${ENVIRONMENT}
  host: '0.0.0.0'
  port: 9999
  workers: 1
  timeout: 900  # 15 min
  hostname: 'petcollection.ru'

logging:
  log_level: info
  log_format: '[%(asctime)s.%(msecs)03d] %(module)10s:%(lineno)-3d %(levelname)-7s - %(message)s'

data_storages:
  main:
    - ${PG_DB_URL}
