networks:
  data_center:
    name: ${NETWORK}
    driver: bridge

services:
  redis:
    image: redis:7.4.0
    container_name: redis_${APP_NAME}__${ENVIRONMENT}
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: ['redis-server', '/usr/local/etc/redis/redis.conf']
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - data_center

  postgres:
    image: postgres
    container_name: postgres_${APP_NAME}__${ENVIRONMENT}
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_DBNAME}
    ports:
      - ${PG_PORT}:5432
    networks:
      - data_center

  grafana:
    image: grafana/grafana
    container_name: grafana_${APP_NAME}__${ENVIRONMENT}
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
    networks:
      - data_center

  adminer:
    image: adminer
    container_name: adminer_${APP_NAME}__${ENVIRONMENT}
    restart: always
    ports:
      - 7777:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    networks:
      - data_center
  
  minio:
    image: quay.io/minio/minio
    container_name: minio_${APP_NAME}__${ENVIRONMENT}
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    networks:
      - data_center
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_${APP_NAME}__${ENVIRONMENT}
    environment:
      - PGADMIN_LISTEN_PORT=5050
      - PGADMIN_DEFAULT_EMAIL=bichokov0405@yandex.ru
      - PGADMIN_DEFAULT_PASSWORD=admin
    networks:
      - data_center
    ports:
      - 5050:5050
  dbeaver:
    image: dbeaver/cloudbeaver
    container_name: dbeaver_${APP_NAME}__${ENVIRONMENT}
    ports:
      - 8978:8978
    networks:
      - data_center
volumes:
  grafana_data:
